"""c5

Revision ID: 229b14fef951
Revises: d13bdd5181a1
Create Date: 2023-06-20 01:47:47.082729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229b14fef951'
down_revision = 'd13bdd5181a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_user_admin',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.PrimaryKeyConstraint('chat_id', 'admin_id')
    )
    op.create_table('user_message_read',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_message_read')
    op.drop_table('chat_user_admin')
    # ### end Alembic commands ###
