"""c3

Revision ID: 293c16b3e87b
Revises: adb4eb1a4b94
Create Date: 2023-06-20 01:05:42.345294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '293c16b3e87b'
down_revision = 'adb4eb1a4b94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
