"""c2

Revision ID: adb4eb1a4b94
Revises: 958bf55cec11
Create Date: 2023-06-20 00:35:32.347068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adb4eb1a4b94'
down_revision = '958bf55cec11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
